kind: pipeline
name: default

steps:
- name: build
  image: ruby:2.7.7
  settings:
    repo: kinnairdclan/coderbears_blog
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
  commands:
    - gem update --system 3.4.2 > /dev/null #This was crazy verbose and --quiet wasn't working
    - gem install bundler
    - bundle install
    - bundle exec jekyll build

- name: push
  image: plugins/docker
  settings:
    repo: kinnairdclan/coderbears_blog
    dockerfile: Dockerfile.production
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
