kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: kinnairdclan/kinnairdclan.github.io
    tags:
      - latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
  commands: 
    - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock
    - apk add --no-cache make
    - make build_dev 
    - make build_prod
    - make push_prod
