#This is a WIP, the "commands" switch makes the container no longer do the nice drone.io things and the make commands therefore struggle to access the docker daemon
kind: pipeline
name: default

steps:
- name: docker-custom
  image: docker
  settings:
    repo: kinnairdclan/kinnairdclan.github.io
    tags:
      - latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
  commands: 
    - apk add --update make
    - docker build --no-cache -t kinnairdclan/coderbears_blog_dev $PWD
    - docker run --rm --volume $PWD:/srv/jekyll kinnairdclan/coderbears_blog_dev bundle exec jekyll build $PWD
    - docker build --no-cache -t kinnairdclan/coderbears_blog -f $PWD/Dockerfile.production $PWD
    - make push_prod
  volumes:
    - name: docker  
      path: /var/run/docker.sock
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
