#This is a WIP, the "commands" switch makes the container no longer do the nice drone.io things and the make commands therefore struggle to access the docker daemon
kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: kinnairdclan/kinnairdclan.github.io
    tags:
      - latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
  commands: 
    - docker build --rm=true --no-cache -t kinnairdclan/coderbears_blog_dev $PWD
    - docker build --rm=true --no-cache -t kinnairdclan/coderbears_blog -f $PWD/Dockerfile.production $PWD
    - docker push kinnairdclan/coderbears_blog:latest
