kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: kinnairdclan/kinnairdclan.github.io
    tags:
      - latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
  commands: 
    - make build_dev 
    - make build_prod
    - make push_prod
